# Generated by Django 2.0.2 on 2022-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cookie1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cookie1', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
